export const ADD_TO_CART_REQUEST = '@cart/ADD_REQUEST';
export const ADD_TO_CART_SUCCESS = '@cart/ADD_SUCCESS';

export const REMOVE_FROM_CART = '@cart/REMOVE';
export const UPDATE_AMOUNT_CART_REQUEST = '@cart/UPDATE_AMOUNT_REQUEST';
export const UPDATE_AMOUNT_CART_SUCCESS = '@cart/UPDATE_AMOUNT_SUCCESS';