on:
  push:
    branches: [ tdc-dash-alternativo ]

name: Cypress + Sorry Cypress Dashboard

jobs:
  deploy:
    name: Cypress Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v2
        id: cypress
        continue-on-error: true
        with:
          start: npm run setup
          wait-on: 'http://localhost:3000'
          command: npm run cy:gh -- --parallel --record --key xxx --ci-build-id '${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate report
        run: npm run allure:report

      - name: Publish gh-pages
        uses: JamesIves/github-pages-deploy-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: allure-report
